### PR TITLE
Avoid arange inadvertently using floating point

### PR DESCRIPTION
**Pull request by mabl**

### CODE REVIEW

**Comment by jordens** [comment]
What's the bug?

**Comment by mabl** [comment]
In latest numpy, float values are not allowed for the num argument of linspace. When integers only are passed to arange, i will be integer, as required.

**Comment by mabl** [comment]
See for example also the test failures in #32 (e.g. https://travis-ci.org/github/quartiq/rayopt/jobs/692676119#L1434)

**Comment by jordens** [comment]
Ack. Then we should just do `range(1, n + 1)` to indicate a programmatic integer range iteration and not so much a numerical grid for an algorithm. Sorry for the unclear code.

**Comment by mabl** [comment]
> Ack. Then we should just do `range(1, n + 1)` to indicate a programmatic integer range iteration and not so much a numerical grid for an algorithm. Sorry for the unclear code.

Correct! I changed it.

**Pull request merged**
